name: Deploy to GitHub

on:
    push:
        branches:
            - main
        paths-ignore:
            - "**/*.md"
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy to GitHub
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3.3.0

            - name: Setup Node
              uses: actions/setup-node@v3.5.1
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build website
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3.9.2
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
                  publish_branch: gh-pages
                  user_name: "github-actions[bot]"
                  user_email: "github-actions[bot]@users.noreply.github.com"
